### ISSUE TITLE
Upgrading dependencies does not show up in npm package

### ISSUE THREAD

**Issue by sshivananda** [RobinBuschmann/xml-typescript#8]
@RobinBuschmann We upgraded the dependencies in [PR#7](https://github.com/RobinBuschmann/xml-typescript/pull/7 ) - but the [node js package](https://www.npmjs.com/package/xml-decorators) still shows the older dependencies.

Is there a separate step for publishing this package?

**Comment by RobinBuschmann** [comment]
@sshivananda Hey sry, yes the package needed to be published again. Now your changes should be available with the latest version `xml-decorators@1.0.8`

**Comment by sshivananda** [comment]
Thanks - closing this one
